services:
  postgres:
    image: 'postgres:15-alpine'
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - '5433:5432'
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data

  kafka:
    image: 'apache/kafka:3.8.0'
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true

      KAFKA_NUM_PARTITIONS: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1

    volumes:
      - kafka-data:/var/lib/kafka/data

    restart: unless-stopped


  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      JWT_SECRET: ${JWT_SECRET}
    restart: unless-stopped

  scheduler:
      build: ./scheduler
      container_name: scheduler
      depends_on:
        - postgres
        - kafka
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
        SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
        SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
        SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      restart: unless-stopped

  email-sender:
      build: ./email-sender
      container_name: email-sender
      depends_on:
        - kafka
      environment:
        SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
        SPRING_MAIL_HOST: smtp.gmail.com
        SPRING_MAIL_PORT: 587
        SPRING_MAIL_USERNAME: ${GMAIL_USERNAME}
        SPRING_MAIL_PASSWORD: ${GMAIL_APP_PASSWORD}
        SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: true
        SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true
      restart: unless-stopped


volumes:
  postgres-data:
    driver: local
  kafka-data:
    driver: local